doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                dbname: '%env(resolve:DATABASE_NAME)%'
                host: '%env(resolve:DATABASE_HOST)%'
                port: '%env(resolve:DATABASE_PORT)%'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PASSWORD)%'
                server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true

        entity_managers:
            default:
                connection: default
                query_cache_driver:
                    type: pool
                    id: doctrine.cache_pool
                result_cache_driver:
                    type: pool
                    id: doctrine.cache_pool
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
