version: '3.8'

services:
  database:
    container_name: ares-db
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aresdb
      MYSQL_USER: ares
      MYSQL_PASSWORD: ares
    ports:
      - '4306:3306'

  php:
    container_name: ares-php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
    depends_on:
      - database

  nginx:
    container_name: ares-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
